rid,rezeptname,Ernaerungskategorien
1,Pizza_Salami,
2,Pizza_Vegan,Vegan
3,Pizza_Vegetarisch,Vegetarisch
4,Nudelpfanne,Vegetarisch
5,Pfannkuchen,Laktosefrei
6,Salat,Vegan
7,GefuelltePaprika,Glutenfrei
8,Gemuesepfanne,Glutenfrei
9,Gemuesepfanne,Vegan
10,Salat,Glutenfrei
11,Pfannkuchen,
12,Kartoffelgratin,Vegetarisch
13,Kartoffelgratin,Glutenfrei
14,Gemuesepfanne,Vegetarisch
15,Gemuesepfanne,
16,Gemuesepfanne,ohneGentechnik
17,Burger,
18,Burger,Vegetarisch
19,Burger,Vegan
20,Burger,ohneGentechnik
21,Burger,LowCarb
22,Gemuesepfanne,LowCarb
23,Brot,Vegan
